### PR TITLE
[sketch] lib/README.md: Super-rough import of comments

### PR DESCRIPTION
**Pull request by lukego**
Very very roughly import the module comments into README.md to get a feel for how the documentation would be structured if we migrated and edited all of this properly.

If this were done properly then would it be an improvement and a step in the direction that we want to take? cc @eugeneia @wingo @kbara.

Note: The `next` branch currently has very poor consistency in terms of documentation style for `lib/`. The master branch has all of these modules documented in comments whereas the `next` branch has devoted the whole of `lib/README.md` to the `ctable` module. I would like to make this consistent *somehow* before we ship the next release.

Question is: should we do this PR properly or should we document `lib/` modules with comments in sources?

### CODE REVIEW

**Comment by lukego** [comment]
First observation: a table of contents is needed to navigate this much content.

**Comment by wingo** [comment]
Regarding lib/README.md, it was requested explicitly by @eugeneia in #722.  I still think lib/README.*module*.md is nicer for browsing on Github, because as you say it is a bit overwhelming to have everything in one vertical scroll, and it seems that GitHub doesn't do tables of contents in markdown files.  Dunno.

**Comment by lukego** [comment]
Could also move each library into a dedicated `lib/foo/` subdirectory with its own README. Then on Github the directory listing would act as a table of contents. Could also hack `require()` to make short names like `require("lib.ctable")` work.

However: I really think we need to nail down which user experience we are trying to optimize foremost. On the one hand if we focus on a stand-alone HTML/PDF/EPUB manual created with `pandoc` then we presumably have a lot of options for structures and showing chapter contents and so on. On the other hand if focus on reading via Github then the file layout is important and we have to make a trade-off between clutter vs latency of clicking around in subdirectory links.

So I think we need to resolve that question over on #758 first i.e. which documentation user experience are we primarily optimizing?

**Comment by eugeneia** [comment]
> Could also move each library into a dedicated lib/foo/ subdirectory with its own README. Then on Github the directory listing would act as a table of contents. Could also hack require() to make short names like require("lib.ctable") work.

I am inclined to go with this and would be willing to refine this PR for that purpose.

> However: I really think we need to nail down which user experience we are trying to optimize foremost. 

I don't think we can get around providing standalone HTML/PDF/EPUB manuals as  the primary target as this is the de-facto standard as far as I can tell. The upside is that this doesn't conflict with organizing the documentation in a GitHub friendly way at all. So I think we can optimize organization for GitHub and render a standalone manual independently without restrictions that arise from this.

**Comment by wingo** [comment]
On Mon 22 Feb 2016 15:10, Max Rottenkolber <notifications@github.com> writes:

>     However: I really think we need to nail down which user experience
>     we are trying to optimize foremost. 
>
> I don't think we can get around providing standalone HTML/PDF/EPUB
> manuals as the primary target as this is the de-facto standard as far as
> I can tell. The upside is that this doesn't conflict with organizing the
> documentation in a GitHub friendly way at all. So I think we can
> optimize organization for GitHub and render a standalone manual
> independently without restrictions that arise from this.

Why not just files in markdown that are meant to be read in github?
Personally I don't see the need for PDF or EPUB at all.  Markdown
documents are easy to improve (once you have a branch with the basic
contents, you can edit online in github to make sure the formatting
looks right; a fairly low-latency cycle) and on github they link really
well to other files, can embed images natively, and ascii art is just as
good as the generated graphs.

I tried hard to avoid giving my opinion but I seem to have failed.  Feel
free to ignore me :)

**Comment by lukego** [comment]
@wingo Fair question. My $0.02 is that the Github UI is too laggy. In practice I am not willing to click around there looking for documentation: I read the sources in my editor instead (like @kbara). I see this as a negative thing because it makes me lose touch with the "real" documentation and not be motivated to improve it.

**Comment by lukego** [comment]
I hope that having a browser tab with the complete Snabb manual open and easy to navigate will fix that situation. (Or if not already open then at least auto-completing as a URL in my browser.)

**Comment by eugeneia** [comment]
> Why not just files in markdown that are meant to be read in github?

While having documentation formatted on GitHub is nice, I feel we can't be limited by GitHub in documentation UI (things like having a ToC etc). Also, Package maintainers for distributions usually want to ship documentation so being able to build a standalone HTML (or maybe even man page one day, I think `pandoc` can do this as well) is useful to them.

**Comment by lukego** [comment]
@capr do you have a suggestion for how we could make `require("foo")` automatically consider `require("foo.foo")` as a fallback? I know that ordinarily the Lua path can be used to make an `init.lua` load but I don't think LuaJIT supports anything like that when loading modules that are compiled into C objects. So we would need to make some kind of extension e.g. wrapper function around `require` or hack the LuaJIT C code or new function in `package.loaders` or ... something?

**Comment by capr** [comment]
@lukego not without any standard-behavior-modifying-magic ;) As you say the `foo/init.lua` convention doesn't work with embedded modules but I guess you could hack the Makefile to generate a temporary `foo.lua` file for each `foo/init.lua` whose contents is `return require'foo.init'` and embed that too. But then all the open files in your editor will be called `init.lua`, ouch.

I know I sound like a broken record, but what's the deal with all the directories anyway? Taxonomic hierarchies (i.e. directories that are not really functional namespaces like `/bin` and `/lib` are in Linux, but cognitive namespaces used solely for classification) only add confusion (eg. `lib` vs `core/lib`) and make you `cd` a lot (or navigate a lot) for no benefit. Modules are APIs and APIs are not hierarchical in nature, the API dependency is a graph. The only legitimate use of directories is for submodules which don't expose an API but serve for breaking down a large implementation, or enable an optional part of the main API, and even then I wouldn't make a directory for less than 20 submodules (`foo_bar.lua` is just fine). That's a long way of saying "don't fight the runtime, work with it".

Also I think the `README.md` convention of github is a terrible idea and promotes deep hierarchies (or cramming unrelated modules into a single doc, take your pick). What's wrong with `foo.md` for each `foo.lua`? Also note that github's flavor of markdown is a small case of vendor lock-in. If you switch to pandoc there might be small incompatibilities that need fixing (no biggie but can be annoying). Alas, pandoc has many cool extensions that won't render on github.

@wingo why did you tried hard to avoid giving your opinion? :)

**Comment by lukego** [comment]
> Modules are APIs and APIs are not hierarchical in nature, the API dependency is a graph. 

The hierarchy is a way of constraining the dependency graph to provide useful structure. Core does not depend on lib, lib does not depend on apps, apps do not depend on programs. The lower layers can be understood completely without reference to the layers above.

This is the same as e.g. a Unix system: the kernel does not depend on libc, libc does not depend on Firefox, etc. This layering seems very typical in my experience i.e. trying to avoid cycles in the dependency graph both between nodes and groups of nodes.

This is practical. For example it allows us to be quite strict in core (refuse duplication, ensure consistency, etc) and a bit more liberal in lib (provide alternative implementations to see which becomes the most popular, introduce new programming styles that may or may not catch on, etc), and downright libertarian in other areas (e.g. allow programs to do whatever they like provided it doesn't mess up the build). Good fences make good neighbours.

**Comment by wingo** [comment]
FWIW, core.lib does import lib.lua.alt_getopt.  Dunno if bug or feature!

**Comment by lukego** [comment]
@wingo I would say that any dependency from core to lib is a bug. The whole `core.lib` module is really a "where should this go, anyway?" miscellaneous dustbin. Refactoring this to be consistent with the layering model would be valuable.

**Comment by lukego** [comment]
@wingo Having said that, there is no big prize for absolute perfect consistency, so it is not an acute problem for a small number of dependencies to break the rules. The main motivation to fix this is the [Fix Broken Windows](http://c2.com/cgi/wiki?FixBrokenWindows) principle.

**Comment by capr** [comment]
The current directory structure doesn't reflect this layering that you're talking about. `lib` and `apps` are both in the root namespace. You have to actually look at the code to see this layering, same as with a flat namespace. From the app dev pov the layering is arbitrary. A dev's question is "show me the spices", not "show me the spice rack". What I think is happening is that those directories are loaded with _policy_ as you explained above, but this policy is not directly visible by users, they only see the directories and wonder what's up with that. So as long as you have to explain the meaning of the layering out-of-band in some documentation, you can have any kind of directory structure or none at all, it's all the same.

**Comment by capr** [comment]
The user wants `require"snabb.spice"` but the layering makes them do `require"snabb.first_row.second_place.spice"`. 

Anyway I think I'm not doing a very good job at explaining this so I'll stop here, but I wanted to at least try. Naming and organizing is complicated business :)

**Comment by lukego** [comment]
@capr So we are talking about two things: the structure of the code - dependency graph - and the presentation to the user - API.

I have described the structure above. This seems sound to me: I don't recognize any objections to this aspect.

I agree that the API is haphazard and that is why I created issue #734. We can work out a better way once @kbara is available to take the lead on that.

Reasonable?

**Comment by lukego** [comment]
@capr Relating the structure vs API idea to Unix too: I see this as like when as a user you call an API function like `clock_gettime()`. Are you calling the kernel? Or the C library? Or the kernel via the C library? You don't really care and the answer may be implementation dependent e.g. the C library may access one time source directly from the CPU and another via the kernel.

**Comment by lukego** [comment]
The filesystem layout is another question. I care much less about that aspect personally.

**Comment by lukego** [comment]
@eugeneia I don't really feel good about releasing `v2016.03` with the documentation style in `lib/` becoming less consistent. I am not sure if we can still fix that. The only solution I see is what both @wingo and @capr have suggested i.e. separate README files in the same directory for each module (`lib/pmu.md`, `lib/ctable.md`, etc). That would avoid the whole mess of moving things into subdirectories and making `require()` still work in the same way. What do you think?

**Comment by eugeneia** [comment]
@lukego I am generally not against `lib/<module>.md` files but I think this leads to a bigger mess and inconsistency than sub-directories and patching require. E.g. without moving files out of sub-directories into `lib/` it would still be inconsistent and I do not think that is what we want. Alternatively we could just move the `README.md` files (e.g. `protocol/README.md -> protocol.md`). The latter I actually see as a viable option, the only downside is that we loose GitHub rendering when browsing the directories.

Is patching `require` off the table? My personal preference would still be to move each library into a sub-directory and patch `require` to load existing files in this order:

```
require("foo") =>
  foo.lua
  foo/foo.lua
```

I do not see right now how this could break things, but making `require` more fancy is obviously a culprit. I generally think we should not rush this decision into 2016.03, is the current situation really that bad?

**Comment by lukego** [comment]
Obsoleted by #790.

**Pull request closed without merging**
