### PR TITLE
Integrate snabb top

### PR DESCRIPTION
**Pull request by eugeneia**
This adds a `snabb top` program. `snabb top` is powered by `core.shm` and `core.counter`. It is not a curses program but uses VT100 term codes to emulate a single updating screen. This works Okayish, suggestions welcome. Consider this a work in progress, its not done yet:

- [x] Implement working `snabb top`
- [ ] Agree on shared memory mapping layout

### CODE REVIEW

**Comment by eugeneia** [comment]
> Make filename used by lib.ipc.shmem.top configurable to allow for multiple Snabb Switch instances (figure out a scheme)

@lukego Do we currently have a policy for where Snabb instance files should go? How about multiple instances? Something like `/var/snabb/<pid>/...` or `/tmp/snabb/<pid>/...` (last one has the advantage of being user writable by default)?

**Comment by lukego** [comment]
Cool! Fanastic! Awesome!

I have this running now:

```
 Kfrees/s        freeGbytes/s    breaths/s      
 1775.38         2.14            5496           

 Links (rx/tx/txdrop in Mpps)    rx      tx      rxGb    txGb    txdrop 
 B_Virtio.tx -> B_NIC.rx         0.19    0.19    0.01    0.01    0.00   
 B_NIC.tx -> B_Virtio.rx         0.70    0.70    1.06    1.06    0.00   
 A_Virtio.tx -> A_NIC.rx         0.70    0.70    1.06    1.06    0.00   
 A_NIC.tx -> A_Virtio.rx         0.19    0.19    0.01    0.01    0.00   
```

I would like to request more detailed usage information and more verbose information while trying to connect to an instance please! My initial attempts to run looked like simply:

```
 ./snabb top 
Connecting...
```

and it was not until I ran with `strace` that I realized it was a permissions issue and I needed to run with `sudo` to be able to open the counter files.

**Comment by lukego** [comment]
Bug report: On this branch when I start a second `snabbnfv traffic` process the first one crashes with a `SIGBUS`. I am not sure if that is expected to work or not at this stage or not.

**Comment by eugeneia** [comment]
@lukego Multiple instances are supported in eugeneia/snabbtop-fs, still a WIP though.

**Comment by lukego** [comment]
I merged this onto `next` to test for the next release. I hope that we will be able to use #513 to more easily expose state from the core and the apps to SnabbTop but we will see.

**Comment by eugeneia** [comment]
> I hope that we will be able to use #513 to more easily expose state from the core and the apps to SnabbTop but we will see.

@lukego Me too, the friction between `lib.ipc.shmem.top` and `core.app` is what I feel most unsatisfied about.

**Comment by lukego** [comment]
Hoi!

How is SnabbTop feeling nowadays? Should I merge this branch? (How come SnabbBot is unhappy?)

**Comment by eugeneia** [comment]
Its not ready yet, I am still working on using the new `core.shm` for `snabb top`. Next release! :)

**Comment by eugeneia** [comment]
@lukego I just pushed a version of `snabb top` that uses `core.shm`/`core.counter`. It shares each links `rxpackets`/... as counters under `/links/<linkspec>/rxpackets`. It also adds a new `configs` counter that gets incremented with each configuration so `snabb top` can tell when to reopen the link counters.

This branch also moves all the engine stats variables into counters under `/engine`. You should read over the code, as it touches quite a bit of the hot path. I am sure we will find things that we want to do differently.

Currently there are a ton of test failures on tests that try to read `link.stats` I assume. But the NFV selftest and `snabb top` run.

**Comment by eugeneia** [comment]
Closing because this branch's history is fubar. I will compile this branch's work in a fresh branch.

**Pull request closed without merging**
