### PR TITLE
Merge max-next/uvilla/1 into next

### PR DESCRIPTION
**Pull request by eugeneia**
Includes: #781 #791 #787 #794 #795

Cc @lukego 

(Is it a good idea to numerate the “merge x into next” PRs? E.g. increment for each merge during a release cycle?)

### CODE REVIEW

**Comment by eugeneia** [comment]
Maybe it would be better to give these kind of PRs unique names. E.g. since he next release will be “Uvilla”, something like “Merge max-next/uvilla/1 into next”.

**Comment by lukego** [comment]
Merged, thanks!

I note that sooner or later we need to address some consistency issues in `src/core`:

- Documentation: in source files or in READMEs? Histogram docs are in the source file. Once the manual is online hopefully we can migrate this all into READMEs. (Until then, meh, I hate reading markdown source so I don't complain about having it in the source files instead.)
- OO/metatables: Having `histogram` use one API style and `counter` use another would seem fine to me in `lib` or `apps` but not in `core`. Perhaps in the future we can unify those modules (and perhaps that will be done with some form of OO...). Something to ponder for later.
- Source formatting. The histogram module lacks spaces before function argument lists. This is a trivial detail but it does strike me in the eyes when reading code in `src/core` and I think one day we should do a PR to make this subtree consistent.

Regarding PR names I am not too fussy. I personally think of releases in terms of numbers (`v2016.04`) and not names (`uvilla`) so please don't depend on me remembering which release is called what. I also think it will not always be clear which release I ultimately merge a PR into e.g. if the PR comes late in the release cycle and changes code that I have spent a lot of time testing/benchmarking but most of the time we will probably have a common idea on this.

One way to provide a symbolic name to a PR would be to use a short-lived branch for the PR that ships a ready-to-merge prefix of your integration branch. You could create the branch with `git checkout -b uvilla-1 max-next` and then PR from that. This would also make it possible to continue merging new changes onto `max-next` while you wait for me to merge. (The Linux world does something similar with PRs that say "Please pull branch `foo` at tag `bar`" but I don't think tags and Github PRs would play well, hence the idea to use short-lived branches instead.)

Just ideas.

**Comment by wingo** [comment]
@lukego Seems to me the way in which `histogram` differs from `counter` is that `histogram` offers the OO metatable.  However like `counter` it also provides the functions.  You do not need to use method syntax.  WDYT about that style?  Perhaps these musings should go to #740.

**Comment by lukego** [comment]
@wingo I have separate thoughts on the local level (#740) and the global level (#734).

Locally it all looks fine. The histogram module exports a well-defined API in a style that is familiar from core Lua modules like `string`.

Globally the change does not really fit it with the surrounding code. Core modules like `engine`, `config`, `packet`, `link`, and `counter` all export a function-calling API. I would like these modules to all be consistent, whether than is with a function-calling API, or with an OOP API, or with the dual-mode option.

I would like to pick a canonical style and adopt that for the whole project. Meanwhile I would prefer not to introduce more diverse styles in the subset of our codebase that is already homogenous i.e. `core/`.

**Pull request merged**
