### PR TITLE
NFV fixes since Jojoba

### PR DESCRIPTION
**Pull request by eugeneia**
This branch neutron-sync-master and neutron-sync-agent more robust and failure proof. Additionally their output is less verbose and now they print timestamped log messages instead.

### CODE REVIEW

**Comment by lukego** [comment]
I have merged this into the `nfv` branch for wider testing now. (Surprised Github doesn' show that? You can see it when examining the individual commits at least.)

**Comment by eugeneia** [comment]
> Is SnabbBot process nfv btw? or do I need to ge my &*@! bench_env
> working again? :)

I assume you mean if SnabbBot will run for PRs on the snabb-nfv repo? No
it won't. I can make it so tomorrow. For now SnabbBot will run every
minute (e.g. as fast as it can) on SnabbCo/snabbswitch though. That is
with a lock so that it won't interfere with itself.

**Comment by lukego** [comment]
Thanks. I would like to have SnabbBot runs on the `nfv` branch too please. I will PR this to master to trigger for now.

**Comment by lukego** [comment]
Merged into `nfv` branch. Will be included on a future PR from there to master.

**Pull request closed without merging**
