### PR TITLE
Merge: Intel10G: better initialization / closing

### PR DESCRIPTION
**Pull request by lukego**
Merge Javier's fine work on more robust initialization and shutdown of the Intel10G app: #360.

### CODE REVIEW

**Comment by lukego** [comment]
@eugeneia I think this test failure is due to SnabbBot running an older version of LuaJIT than the one reference in our deps/luajit submodule. Can you check? (Is there a special step needed for SnabbBot and developers in general to pick up the latest LuaJIT? If so I wonder if we can solve that in the Makefile?)

This is the tell-tale error that should mean out-of-date LuaJIT:

    Invalid DMA address: 0x500438aedf00
    core/memory.lua:95: DMA address tag check failed

**Comment by eugeneia** [comment]
The reason this happens (i think)is because SnabbBot will:

* clone the repo
* checkout the base (old submodule)
* fetch submodules
* build / test
* checkout HEAD
* build / test again

Strictly speaking its an error SnabbBot I guess, it should update the submodules after every checkout.

**Comment by lukego** [comment]
Guys, how is intel10g reliability for you now on master?

I am seeing diverse errors and warnings when I run in a loop: `never got link up`, `sq_sq: missing packets`, `mq_sq: wrong proprtion`, `transmit counter did not increase`. So to me it seems like we currently have a high-priority bug that NIC initialization is not dependable?

**Comment by lukego** [comment]
Here is output of 100 runs on master for me, with the new Interlake server: https://gist.github.com/lukego/bda37923f504e0c4f71f

Could be that I broke something in merge too.. whatever the case, we need to put this problem behind us quickly.

**Pull request merged**
