### PR TITLE
next: accepted changes for the next release

### PR DESCRIPTION
**Pull request by lukego**
Collection of all changes accepted for the next release. Incrementally updated as more changes are accepted. See #497 for workflow.

### CODE REVIEW

**Comment by lukego** [comment]
Here are a few commands for seeing what is coming in the next release by inspecting the `next` branch:

    # First make sure we have the latest changes on all the branches
    $ git fetch origin

Who wrote the code being tested on `next`?

    $ git shortlog -sn --no-merges master..next                                                    
	15  Max Rottenkolber
	 7  Luke Gorrie
	 3  Alexander Gall
	 1  Edward Hope-Morley

And what are the changes exactly?

    $ git shortlog --no-merges master..next
    Alexander Gall (3):
	  Modify checksum API
	  Apply new IP checksum API
	  Fix type casts for commit 5cc2c1f

    Edward Hope-Morley (1):
	  Fix neutron2snabb parser db schema

    Luke Gorrie (7):
	  neutron2snabb: Fix for security group -> pflua translation
	  neutron2snabb: Added automatic database schema detection
	  neutron2snabb: Fix selftest for security group translation
	  snabbnfv traffic: Check PCI device exists and is supported
	  neutron_sync_agent.sh: Fix to use qualified paths
	  neutron_sync_master: Include *.sql table definitions
	  neutron2snabb: Fix schema selftest to find database files

    Max Rottenkolber (15):
	  Import "Documentation Guide" from Wiki.
	  [documentation guide] Mention different target audiences for     documentation.
	  [neutron-sync-master] Only amend commit when SQL dump actually     changes.
	  [neutron-sync-*] Don't print command outputs and print timestamped log     messages instead.
	  [neutron-sync-agent] Don't try to generate configurations if repository     coild not be successfully cloned.
	  [neutron-sync-agent] Add TMP_DIR and SYNC_PORT options.
	  [neutron-sync-agent] Do not treat "$TMP_DIR/*" as file in `$TMP_DIR' is     empty.
	  [neutron-sync-agent] Only try updating confs when `git diff'     return 1 as opposed to failing with other error codes (>1).
	  [neutron2snabb] Recover selftest.sh (should have really been in     7e9477)
	  [neutron-sync-*] Do not hide output of neutron2snabb and mysqldump.
	  [neutron_sync_master] Update default tables in Lua wrapper.
	  [neutron-sync-master] Remove the '-t' that prevents the table     info from being stored in *.sql. Add '--skip-dump-date' so that     these files don't include a timestamp that makes it look like     something changes between runs.
	  [neutron-sync-agent] Less verbose `git clone' and `git fetch'.
	  [snabbnfv] Import documentation from snabb-nfv Wiki.
	  [snabbnfv] Deleted outdated src/program/snabbnfv/doc/neutron-configuration.md.

And which branches are the Pull Requests being merged into on the way to master? (Some directly onto `next` and others collected on `nfv` and then merged from there.)

    $ git log --oneline --merges --graph next
    *   affd604 Merge PR #501 into next
    |\  
    | * 3607df8 Merge commit 'pr/499' into nfv
    * | e750506 Merge PR #479 into next
    * | cc0ebb9 Merge commit 'pr/494' into next
    * |   183d9c5 Merge branch 'nfv' into next (tag: v2015.05.nfv1)
    |\ \  
    | |/  
    | * 3a71bac Merge commit 'refs/pull/upstream/492' into nfv
    | * 8ccc900 Merge commit 'refs/pull/upstream/491' into nfv
    | * 7cc3f9c Merge commit 'refs/pull/upstream/490' into nfv
    | * 133f855 Merge commit 'refs/pull/upstream/487' into nfv
    | * 5e9369c Merge commit 'refs/pull/upstream/489' into nfv
    | * 3d6d8c8 Merge commit 'refs/pull/upstream/488' into nfv
    | * 7c8a58d Merge commit 'refs/pull/upstream/486' into nfv
    | * 39a8f76 Merge PR #486 into nfv
    * | ce5142d Merge PR #485: branches.md
    |/  
    * 9dae83a Merge pull request #477 from lukego/64bit-registers-merge
    | * 188bc06 Merge PR #475 (Intel 10G 64-bit counters w/ SNMP support)
    |/  
    * b6a4f8e Merge pull request #473 from lukego/README2

We could adapt our git usage to make the output of such commands nicer e.g. I can try to include the most relevant information on the merge commit messages.

**Comment by eugeneia** [comment]
@lukego f5f7175 was not ready please merge the rest of the PR. (It's quite usable now).

**Comment by lukego** [comment]
@eugeneia Thanks for catching that. I had locally merged that onto next for testing, and had not meant to push it to the repository.

Now we are quite close to release time. Is it better to merge the follow-on changes or to revert the change and then reapply immediately after the June release?

**Comment by lukego** [comment]
@eugeneia I think revert is best right now. This is a bit of an uncomfortably large change to pull in before a release, and I had not actually meant to do it now. Could be that e.g. we break startup on certain platforms due to directory names/permissions etc and I would like a chance to debug that before releasing.

This will also give me a chance to test my new understanding of the workflow for reverting and then reintroducing merges :-)

Based on my reading of the [undo merges howto](https://www.kernel.org/pub/software/scm/git/docs/howto/revert-a-faulty-merge.txt) the steps will be:

1. Merge code too early.
2. Revert the merge of partially finished code.
3. Make the new release.
4. Introduce the latest code by first reverting the revert (get back to the partial state) and then pull the remainder from the topic branch.

**Comment by eugeneia** [comment]
Yeah I hadn't intended for snabb top to land in `next` either. Let's give it more testing next month.

**Pull request merged**
