### PR TITLE
Dynasm all the vregs

### PR DESCRIPTION
**Pull request by andywingo**
This merges the LuaJIT updates from https://github.com/eugeneia/snabbswitch/commits/esp into next.  The PR is based on master. Cc @eugeneia.

### CODE REVIEW

**Comment by andywingo** [comment]
Unfortunately I am still not able to use ymm(n) for n >= 8 on this branch.  Perhaps @corsix knows what commits I'm missing.  I did the merge with --strategy=subtree.

The error:
```
dasm error: variable register out of range. :40
```

**Comment by eugeneia** [comment]
I think you ran into the same issue as I did: You merged the LuaJIT patches but left the Snabb-DynASM-bridge (`snabbswitch/src/dasm_*`) untouched. @capr is in the process of updating the latter. See https://github.com/eugeneia/snabbswitch/pull/8#issuecomment-169983464

**Comment by andywingo** [comment]
OK :) I'll follow @capr's work and close this branch if it's eventually unneeded.

**Comment by andywingo** [comment]
FWIW manually examined the DynASM changes and copied them into the Lua DynASM.  This branch seems to work for me.

**Comment by andywingo** [comment]
Cc @capr -- should I submit a patch to your DynASM repo?

**Comment by andywingo** [comment]
Pretty sure the failing build is a failure of the bot (stale checkout).  I think this one is good to go.  Been using it in https://github.com/Igalia/snabbswitch/pull/204.

**Comment by eugeneia** [comment]
Re: failing build. I agree but I can't really tell why it happens (repeatedl)y for this PR.

**Comment by lukego** [comment]
The compile error is due to luajit/luajit#126. The workaround is to `make clean` (or `git clean` with suitable args). Just have to accept this. (Perhaps our Makefile could somehow suggest a `make clean` if the build of a dependency fails.)

Looks like @eugeneia already did the `git subtree pull` and I needn't have bothered with #715.

**Comment by lukego** [comment]
@eugeneia next step is you merge this onto `max-next`?

**Pull request closed without merging**
