### PR TITLE
next: collected changes for v2015.07 release

### PR DESCRIPTION
**Pull request by lukego**
Commits are added to this Pull Request as they are merged for integration into the v2015.07 release.

### CODE REVIEW

**Comment by lukego** [comment]
Interesting test failure. Looks like luajit and pflua upgrades each worked individually (#506 and #507 passed CI) but seem to have trouble when combined together and with the latest Snabb release? I will take a look at this tomorrow.

**Comment by lukego** [comment]
Interesting. SnabbBot is failing the current build with `program.snabbnfv.nfvconfig` triggering an error in pflua ([log](https://gist.github.com/SnabbBot/8fbed2912cfa49228602#file-log-L490-L514)). However, this is not reproducible on my development machine.

I wonder if recent LuaJIT versions have introduce changes that break pflua? That seemed to happen with issue Igalia/pflua#225 which reproducibly happens only with the LuaJIT update that we have on this branch.

**Comment by kbara** [comment]
This is still a work in progress, but the analysis on 225 (especially by mpeterv) shows pretty conclusively that this is a LuaJIT issue. I'd be tempted to stick with LuaJIT 2.0.x if I were you; when I benchmarked them last year, it was faster, and it's also more stable.
Diego and I have both been able to intermittently reproduce the problem on our development machines by running ```sudo ./snabb snsh -t apps.packet_filter.pcap_filter``` (with version 8ac912d21c817f86618b6588ad13e23260deeea6 from the 'next' branch).
It can also be reproduced within pflua head without Snabb by running ```./env pflua-compile "(icmp6 and src net 3ffe:501:0:1001::2/128 and dst net 3ffe:507:0:1:200:86ff:fe05:8000/116) or (ip6 and udp and src net 3ffe:500::/28 and dst net 3ffe:0501:4819::/64 and src portrange 2397-2399 and dst port 53)"```; see mpeterv's analysis for how the details change between specific LuaJIT 2.1 commits.

**Comment by lukego** [comment]
Interesting idea to use the stable LuaJIT v2.0.x. I am not sure if that would be realistic or not. Snabb Switch has used the v2.1 branch from the beginning and there are at least some new features of interest, like the profiler and 64-bit bitops.

So var v2.1 has been quite good to use and I do think it's supposed to be fairly stable. I think that Cloudflare run v2.1 in production on billions of HTTP requests per day. Could be an idea to ask them how they handle updates.

**Comment by kbara** [comment]
Good points, and having 64-bit bitops is pretty nice; I'd be curious to know how Cloudflare's handling upgrades too.

**Comment by lukego** [comment]
Seems like the LuaJIT+pflua upgrade problem is caused by bug(s) in the latest LuaJIT. So with hindsight it would have been better to revert LuaJIT upgrade instead of pflua.

Hopefully LuaJIT will have a fix shortly and we can merge that. Otherwise we could revert the LuaJIT upgrade and un-revert the pflua upgrade for this month. Let's give it a few days and see.

**Comment by lukego** [comment]
@eugeneia any insight into this test failure? Seems like the tests passed by performance regressed to 0? :-)

**Comment by eugeneia** [comment]
@lukego I had SnabbBot rerun it and it seems fine now.

**Comment by kbara** [comment]
@lukego The problem is fixed with LuaJIT fe565222a1cbf28fbae266da35c8a703fdcfa0dd , which disables the optimization you correctly bisected the problem to. I've checked the fix with both pflua-compile and ```sudo ./snabb snsh -t apps.packet_filter.pcap_filter```, and everything appears to be fine, though I haven't run extensive tests beyond that.

**Comment by lukego** [comment]
Awesome work @kbara and the pflua team! I prepared PR #520 to reintroduce the pflua upgrade together with the compatible LuaJIT and will merge that here once it passes CI.

Your hard work to create minimal test cases is a real contribution to LuaJIT and Mike's to collection of reproducible test cases for the future.

**Comment by eugeneia** [comment]
If you wonder while this failed: don't. Rerunning it now.

**Comment by eugeneia** [comment]
@lukego How are we doing on the release? I could do it today. Couldn't hurt to include #530 and #531 as well.

**Comment by lukego** [comment]
@eugeneia Merged as requested. I am ready for release if you/SnabbBot don't see problems.

**Comment by eugeneia** [comment]
https://github.com/SnabbCo/snabbswitch/releases/tag/v2015.07

**Pull request merged**
