### PR TITLE
Add RateLimitedRepeater to basic_apps

### PR DESCRIPTION
**Pull request by wingo**
This app is useful for generating different load levels.  No documentation because the documentation files changed name in next and this is based on master, and the basic_apps documentation doesn't currently specify anything about the API of those applications, so documentation seems to be a moot point currently.

### CODE REVIEW

**Comment by eugeneia** [comment]
I think this is too fancy for `apps.basic_apps` and belongs under `apps.test.*`. What do you think @lukego?

**Comment by wingo** [comment]
Sure, or `apps.rate_limiter`; dunno.  Or, perhaps we could add a mode to the RateLimiter that doesn't discard packets.

**Comment by wingo** [comment]
Somewhat related to the #656.

**Comment by eugeneia** [comment]
@wingo I like the idea of extending `RateLimiter` and combining it with `Repeater`. It seems like a nice composing solution, but the choice is yours.

**Comment by mwiget** [comment]
@wingo I like the idea as well. While one could chain a RateLimiter after the  Repeater app, it burns avoidable CPU cycles by first creating the packets, then dropping them mid flight. Had to combine RateLimiter also in my crude snabb based lwaftr flow generator in order to have enough CPU cycles to count incoming traffic.

**Comment by wingo** [comment]
Closing this one; #793 is the successor.

**Pull request closed without merging**
