### PR TITLE
Implement PCI address expansion

### PR DESCRIPTION
**Pull request by dpino**
Adds function `expand_pciaddr` which expands a PCI address to BDF format http://wiki.xenproject.org/wiki/Bus:Device.Function_%28BDF%29_Notation

Example:

* "1:"                   => 0000:01:00.0
* "01:"                 => 0000:01:00.0
* "01:00.0"          => 0000:01:00.0
* ":01:"                => 0000:01:00.0
* "0000:01:"        => 0000:01:00.0
* "0000:01:00.0" => 0000:01:00.0
* ":1"                   => 0000:00:01.0
* "1"                    => 0000:00:01.0

A single number is interpreted as a device and all the empty elements are filled up with zeroes. Semicolons tell what position an element occupies in the BDF pattern. For instance, ":1" tells everything to the left is empty and the element ends up occupying the device position. On the other hand, "1:" tells everything to the right is empty, the element ends up occupying the bus position and PCI is filled up with zeroes. This pattern is the same as ":1:".

This PR solves #657.

### CODE REVIEW

**Comment by eugeneia** [comment]
All the PCI addresses I ever needed to type when working with Snabb Switch have the form `0000:XX:00.Y`. So a far as I can tell I only need a pattern `XX:.Y := 0000:XX:00.Y`. Is this coincidental? When are the domain/device fields relevant, does it depend on the specific hardware?

**Comment by kbara** [comment]
@eugeneia I asked basically the same in https://github.com/SnabbCo/snabbswitch/pull/641 , and Luke pointed me to http://wiki.xenproject.org/wiki/Bus:Device.Function_%28BDF%29_Notation , which doesn't fully answer this but gives some interesting context.

**Comment by dpino** [comment]
Before I was working with the virtio_net driver I thought the only use case for PCI address simplification would be the pattern you describe "XX:00.Y" which could be conveniently write as "04:00.1", for instance. 

The virtio_net driver takes a PCI address from devices at _/sys/class/net_, which in the VM I use for testing have the form "00:0X.Y" (many devices in my laptop at _/sys/bus/pci/devices_ follow this pattern too). A PCI address were device is the only significant part could be simplified as ":04.0"  or "4.0" or even "4". I think most of the time we will be dealing with this two type of addresses. The multiple examples are there to show the function works well and it's consistent. Basically what it does is to fill up with zeros what's left unwritten.

**Comment by lukego** [comment]
@eugeneia I believe it is hardware dependent, yes. The network cards we are working with are pretty simple e.g. one ethernet controller chip with two ports attached to it. There could be others that e.g. combine multiple ethernet chips multiplexed behind a PCIe switching chip. Companies like [Silicom](http://silicom-usa.com/] make a lot of interesting cards in this direction. I don't know exactly how the PCIe addresses will end up looking but I wouldn't want to make too many assumptions based on the cards we have in the lab today.

@dpino I am surprised that the virtio-net driver doesn't identify the device by a PCI address exactly like the Intel10G one? (Why does `/sys/class/net` come into the picture? Can discuss this on that PR branch though.)

**Comment by eugeneia** [comment]
Is this PR obsoleted by #669  and can be closed?

**Comment by dpino** [comment]
@eugeneia Right. Closed PR.

**Pull request closed without merging**
