### PR TITLE
next: Collected changes for the v2015.09 release

### PR DESCRIPTION
**Pull request by lukego**
This Pull Request contains the changes that are being tested for inclusion in the v2015.09 branch.

### CODE REVIEW

**Comment by lukego** [comment]
Looks like the test failure here is an operational issue (hugepage availability on the CI host). That is no biggie: the next merge will trigger a rerun anyway.

Does raise a couple of interesting thoughts though:

1. How come the hugepage is failing to allocate? In the log we see that Snabb Switch makes three attempts to provision a new huge page in the kernel and then allocate that. I wonder why those attempts are all failing and whether we could improve that algorithm to make it more robust.
2. I see that it would be valuable to run the CI on multiple hosts so that CI operational issues are easier to distinguish. If the CI result were that tests passed on 4/5 CI servers then it would be easier to estimate confidence in the code before digging into the root cause. Once more I see docker (Issue #588) as the great hope to make it easy to operate a CI fleet.

**Comment by eugeneia** [comment]
@lukego I take it we're ready for release here? If so, I will go ahead and do the routine.

**Comment by lukego** [comment]
Roger!

**Comment by lukego** [comment]
Humble request: Could you put the release name in the first line of the commit message when you merge onto master? Just so that it is immediately visible in one-line summaries e.g. `git log --oneline`.

For example

    Merged PR #593 (v2015.09 release) onto master

**Pull request merged**
