### PR TITLE
NFV patches for next

### LINKED ISSUE #592: Low performance for VM2VM in v2015.08
We are using the following script for VM2VM performance evaluation:

```lua
local VhostUser = require("apps.vhost.vhost_user").VhostUser

local c = config.new()
config.app(c, "vh1", VhostUser, {socket_path="/tmp/vh1.sock", is_server=false})
config.app(c, "vh2", VhostUser, {socket_path="/tmp/vh2.sock", is_server=false})

config.link(c, "vh1.tx -> vh2.rx")
config.link(c, "vh2.tx -> vh1.rx")

engine.configure(c)
engine.main()
```
This script is run using `snsh` and attached to the NUMA node where the 2 VMs are running.
Inside the VMs we use a packet generator based on DPDK from here http://dpdk.org/browse/apps/pktgen-dpdk/ The performance test is to send 64byte UDP packets from one VM and measure the received ones using `pktgen-dpdk` in the other VM.

<pre>
+-----+---------+     +-----+---------+                  
|     |         |     |     |         |                  
|VM1  | PKTGEN  |     |VM2  | PKTGEN  |                  
|     |         |     |     |         |                  
|     +---------+     |     +---------+                  
|     |         |     |     |         |                  
|     |  DPDK   |     |     |  DPDK   |                  
|     |         |     |     |         |                  
+-----+-----+---+     +-----+---+-----+                  
            |                   |                        
            |                   |                        
+-----------v-------------------v-----+                  
|                                     |                  
|           SnabbSwitch               |                  
|                                     |                  
|       snsh vhost2vhost.lua          |                  
|                                     |                  
+-------------------------------------+                  

</pre>

The test are run on a `E5-2637 v3 @ 3.50GHz` dual socket machine.

When using `v2015.07.1` we are seeing about `12.7 Mpps` passed to the receiving machine.
With the latest `master` aka `v2015.08` the same performance test shows `9.3 Mpps`.

### PR DESCRIPTION
**Pull request by nnikolaev-virtualopensystems**
This pull request contains 2 patches:
 - add vosys-nfv branch description in branches.md
 - cache counter functions in an attempt to fix #592

### CODE REVIEW

**Comment by lukego** [comment]
Cool! Let us do a Git/Github workflow geek out :-)

I think that 874e8b should be submitted in its own PR based on master for test and review. I don't want to pull it immediately because I don't know whether it is the right thing or not. Commit message only says that it attempts to solve a problem but not that it actually does :-).

The branch `vosys-nfv` has the stated purpose in branches.md that it is for sending changes upstream. In this case I think that only "known good" changes should be pushed onto this branch after they are tested and reviewed. There is no formal definition of how test and review should be done: I only ask that you push changes that work and that don't contain things that will make me complain :-). The easiest way to do that today would be to post the changes as individual PRs on Github and get feedback from anybody who is interested before merging them onto `vosys-nfv`.

also: Once we add `vosys-nfv` to `branches.md` it will be mirrored automatically onto the SnabbCo repo and anybody should be able to write `git checkout vosys-nfv` to run it. The mirroring script currently does not allow rebasing: if you would rebase the branch then it will stop synchronizing until you rebase it back again. This is meant as a feature: the branches are for publishing code for other people to merge and nobody wants to merge from a branch that is being rebased onto a long-lived branch.

note: PR branches are also not supposed to be rebased. If I merge a branch onto `fixes` or `next` and then it gets rebased then I have a major headache on my hands. Likewise everybody else maintaining a long lived branch. I would actually like to find a way for Github to disallow rebasing PRs. The intention of branches being PR'd should either be that they will eventually be merged or that they are dead-ends that will be replaced by a new (rebased) branch later. Branches that are dead-ends should be marked as "draft" and people should not merge them into long-lived branches like `next`. (More in [git-workflow.md](https://github.com/SnabbCo/snabbswitch/blob/master/src/doc/git-workflow.md)).

How does this sound? make sense? something we should change? we don't have so much experience with this workflow yet but it has been working well so far and seems to match the kernel process AFAIK.

**Comment by lukego** [comment]
btw: another nice use for the `vosys-nfv` branch is that it is a mechanism for you guys to take the lead on integrating changes if you want to. For example when somebody submits an NFV-related PR that you are interested in we could assign that to you and you could work on test/review to bring it into `vosys-nfv` and then pushing it onwards to `next` from there.

This how I see the evolution towards the Linux kernel subsystem maintainer model where each change is initially targeted to a specific person and branch and then moves upstream after it has been accepted there.

**Comment by nnikolaev-virtualopensystems** [comment]
@lukego I understand about separate PRs, reviews etc. Then I am not sure why not just merge the PRs themselves instead of moving the patches to `vosys-nfv` and merge from there?

Can you clarify what "rebasing" means here: "if you would rebase the branch then it will stop synchronizing until you rebase it back again." From what I can tell all development is done against `master` (btw nice git-workflow.md ), so rebasing to me happens only when new `master` appears.

Is there a way that I get subscribed to receive mail notifications once new PR appears? It will be easier to monitor an pick whatever is important to us.

**Comment by lukego** [comment]
... one more idea would be to make `vosys-nfv` the best branch for `snabbnfv` users in general. For example by being the fastest to merge good fixes/features from PRs and also doing extra testing when merging new releases from `master` e.g. to deal with regressions like #592 before it is pushed onto your branch. You could also do your own releases off that branch, etc, if you want to. Just an idea. It would certainly make it easy for me to pull from that branch onto `next` if you guys are treating it as production code. (Kind of like the way Redhat &co have their own branch of the kernel that is probably a better choice for many users than Linus's upstream tree.)

**Comment by lukego** [comment]
> Then I am not sure why not just merge the PRs themselves instead of moving the patches to vosys-nfv and merge from there?

You are right. If the only intention is to push code upstream then it is fine to PR it from a topic branch. We don't need a separate `vosys-nfv` branch for that purpose.

The main reason for a separate branch is if you want to have a branch that you control and publish that to all users, who can either run it directly or merge it into their own branches. For example if somebody is supporting a Snabb based application then they might want to have their own branch for that where they can control what is merged and when, and users might want to see that branch mirrored into the main repository where it is easy to compare it with upstream e.g. via the [Github branch list](https://github.com/SnabbCo/snabbswitch/branches/all).

> Can you clarify what "rebasing" means here

I mean that because we now use a merge-based workflow it is not okay to `git push --force` to published branches (including Pull Requests). This is so that everybody can safely merge from PRs and other branches into their own branches (e.g. as I do with `next`). If people do force pushes then it causes problems and conflicts for people who already merged the previous version. I think the [Git DMZ Flow](https://gist.github.com/djspiewak/9f2f91085607a4859a66) document explained this idea best.

> btw nice git-workflow.md

Thanks! :-)

> Is there a way that I get subscribed to receive mail notifications once new PR appears? It will be easier to monitor an pick whatever is important to us.

Great question! Here are the tips that I am picking up for staying on top of Github activity - working well for me now:

1. If you have the repository "Watched" (not just Starred) then you should get email notifications about issues and PRs.
2. If you go to the [Github front page](http://github.com/) you should see a list of the latest activity for all the projects you are tracking. In the beginning this was extremely noisy for me but I solved that by not following so many Github users. Now it is very relevant.
3. I use the [iOctocat](https://ioctocat.com/) iPhone app that makes it very easy to browse notifications, Issues, PRs, etc.

There is probably a blog somewhere with much better tips than this. Originally I found Github very hard to communicate with but nowadays I use it more than Gmail.

**Pull request closed without merging**
