### PR TITLE
next: Collected changes for the v2015.11 release

### PR DESCRIPTION
**Pull request by lukego**
This branch contains the changes being tested for inclusion in the v2015.11 release.

Sorry to open the next branch so late this month! Have been busy. I merged all the simple open PRs and will try to merge the larger ones early in the next cycle. Thanks everybody for contributing to test and review of these changes!

### CODE REVIEW

**Comment by lukego** [comment]
Interesting. Packetblaster is segfaulting on the CI. Anybody know why?

**Comment by eugeneia** [comment]
I was able reproduce the bug, but not deterministically. Try:

```
for i in $(seq 100); do sudo SNABB_TEST_INTEL10G_PCIDEVA=0000:84:00.0 program/packetblaster/selftest.sh || break; done
```

Its an *old* regression, it goes back beyond `v2015.10`. I wasn't able to test `v2015.09` yet ( can not get 5feb63a465c39b65cd9c554e63684eeaae9848f5 from http://luajit.org/git/luajit-2.0.git).

**Comment by lukego** [comment]
Interesting! Thanks for digging. Have to get to the bottom of that.

**Comment by eugeneia** [comment]
Should I rerun SnabbBot on `next`? Since this regression exceeds this release cycle I don't think it should block the release.

**Comment by lukego** [comment]
Agree. Yes, please do.

**Comment by eugeneia** [comment]
@lukego Done.

**Pull request merged**
